spring:
  application:
    name: sca-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        ip: 127.0.0.1
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
      datasource.ds.nacos:
        server-addr: localhost:8848
        data-id: sentinel-flow-rule
        rule-type: flow

logging.level.org.springframework.cloud.stream.binder.rocketmq: DEBUG
logging.level.com.alibaba.nacos: ERROR

spring.cloud.stream:
  rocketmq:
    bindings:
      output.producer:
        group: producer-binder-group
        send-message-timeout: 30000
      springCloudBusOutput.producer:
        send-message-timeout: 30000
#      sync: true
    binder.name-server: localhost:9876
  bindings:
    output:
      destination: binder-topic
      content-type: application/json
    springCloudBusInput:
      destination: springCloudBus
    springCloudBusOutput:
      destination: springCloudBus

server:
  port: 20000

management:
  endpoints:
    web:
      exposure:
        include: "*"

# ------ custom config

custom.config.location: beijing
custom.config.date: 2019-03-21
custom.config.room: 305
